### ISSUE TITLE
In chapter7, I run into this problem: IndexError at / list index out of range <code:ndim = mobjs[0].ndim>

### ISSUE THREAD

**Issue by miaojin7** [PacktPublishing/Machine-Learning-for-the-Web#1]
I already checked the data directory 
[umatrixpath: '/Users/jmirv/Desktop/MachineLearningfortheWeb_Code/chapter_7/server_movierecsys/umatrix.csv'].
Anyone help me solve this!! 
Thx in advance.

**Comment by geomars** [comment]
In *books_recsys_app/views.py* just change the line to **umatrixpath = '../umatrix.csv'**. Since the structure of chapter_7/server_movierecsys is like this:
.
├── books_recsys_app
│   ├── admin.py
│   ├── api.py
│   ├── __init__.py
│   ├── models.py
│   ├── serializers.py
│   ├── tests.py
│   └── views.py
├── server_movierecsys
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── static
│   ├── css 
│   └── js       
├── templates
│   └── books_recsys_app
│       ├── base.html
│       ├── ....
│       └── userexistsorproblem.html
├── db.sqlite3
├── manage.py
├── plots_bk.csv
├── plots.csv
└── umatrix.csv

**Comment by sonam-packt** [comment]
Please reopen the issue if still persist.
